### ISSUE TITLE
Error loading config file.: open ./conf.json:

### ISSUE THREAD

**Issue by todaycx** [MajorMJR/factorio-server-manager#24]
steps:
1 docker build -t factorio-server-manager .
2 docker run --name factorio-manager -d -p 80:80 -p 443:443 -p 34197:34197/udp factorio-server-manager
3 docker logs factorio-manager
then...

2016-05-03 13:00:04:2016/05/03 05:00:04 Error loading config file.: open ./conf.json: no such file or directory
2016-05-03 13:00:04:panic: Error loading config file.: open ./conf.json: no such file or directory
2016-05-03 13:00:04:
2016-05-03 13:00:04:goroutine 1 [running]:
2016-05-03 13:00:04:panic(0x80b500, 0xc820011750)
2016-05-03 13:00:04:	/usr/local/go/src/runtime/panic.go:464 +0x3e6
2016-05-03 13:00:04:main.failOnError(0x7f91187b3778, 0xc82000b770, 0x9edb80, 0x1a)
2016-05-03 13:00:04:	/home/mitch/prog/go/src/github.com/majormjr/factorio-server-manager/main.go:36 +0x2f8
2016-05-03 13:00:04:main.loadServerConfig(0x98b070, 0xb)
2016-05-03 13:00:04:	/home/mitch/prog/go/src/github.com/majormjr/factorio-server-manager/main.go:45 +0x79
2016-05-03 13:00:04:main.main()
2016-05-03 13:00:04:	/home/mitch/prog/go/src/github.com/majormjr/factorio-server-manager/main.go:75 +0x46
2016-05-03 13:00:05:2016/05/03 05:00:05 Error loading config file.: open ./conf.json: no such file or directory
2016-05-03 13:00:05:panic: Error loading config file.: open ./conf.json: no such file or directory
2016-05-03 13:00:05:

**Comment by todaycx** [comment]
MANAGER_VERSION=0.2.0 is ok

**Comment by MajorMJR** [comment]
Hi @todaycx 

I've fixed this issue in version 0.3.1, I've added a flag for the location of the configuration file when launching FSM.  This fixes the issue with launching the docker container.
